version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
        - ./app:/app
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  mysql:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: 'dev'
        MYSQL_USER: 'dev'
        MYSQL_PASSWORD: 'dev'
        MYSQL_DATABASE: 'development'
    volumes:
        - mysqldata:/var/lib/mysql
    ports:
        - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # SMTP server
      - 8280:8025 # web interface

volumes:
    mysqldata: {}
